#!/usr/bin/env python3
"""
Context Manager for Claude Code
Session summarization, archival, and context injection.

Reads today's observation JSONL, generates a rich session summary via:
  1. Gemini CLI (best free option, semantic understanding)
  2. Ollama llama3 (local, free, zero network)
  3. Structured fallback (pure Python, no LLM required)

Summary is saved to session-buffer.md and archived permanently.

Copyright (c) 2026 Jonathan Hobman (Jonohobs), AI Hot Sauce, Claude Code (Anthropic)
License: MIT
Repository: https://github.com/Jonohobs/ai-hot-sauce
Created: 2026-03-18
"""

import json
import os
import subprocess
import sys
from collections import Counter
from datetime import datetime
from pathlib import Path

LOG_DIR = Path.home() / ".claude" / "memory-log"
ARCHIVE_DIR = LOG_DIR / "archive"
BUFFER_FILE = LOG_DIR / "session-buffer.md"
TODAY = datetime.now().strftime("%Y-%m-%d")
NOW = datetime.now().strftime("%H-%M")
OBS_FILE = LOG_DIR / f"observations-{TODAY}.jsonl"


def load_observations():
    if not OBS_FILE.exists() or OBS_FILE.stat().st_size == 0:
        return []
    lines = []
    with open(OBS_FILE) as f:
        for line in f:
            line = line.strip()
            if line:
                try:
                    lines.append(json.loads(line))
                except Exception:
                    pass
    return lines


def build_structured_summary(obs):
    """Fallback: build a structured summary from raw observations without any LLM."""
    if not obs:
        return None

    tools = Counter(o.get("tool", "?") for o in obs)
    tool_summary = ", ".join(f"{t}({c})" for t, c in tools.most_common(10))

    files = set()
    for o in obs:
        s = o.get("summary", "")
        if "/" in s or "\\" in s:
            parts = s.replace("\\", "/").split("/")
            fname = parts[-1][:60] if parts[-1] else ""
            if fname and len(fname) > 2:
                files.add(fname)
    files_str = ", ".join(sorted(files)[:15]) if files else "none"

    first = obs[0].get("time", "?")
    last = obs[-1].get("time", "?")

    actions = [
        o for o in obs
        if o.get("tool") in ("Bash", "Write", "Edit", "Agent", "WebSearch", "WebFetch")
    ]
    action_lines = []
    for a in actions[-12:]:
        s = a.get("summary", "")[:100]
        if s:
            action_lines.append(f"  - [{a.get('tool')}] {s}")

    lines = [
        f"## Session Summary — {TODAY} {first}–{last}",
        f"**Tool usage ({len(obs)} total):** {tool_summary}",
        f"**Files touched:** {files_str}",
    ]
    if action_lines:
        lines.append("**Key actions:**")
        lines.extend(action_lines)
    lines.append("\n_Generated by structured fallback (no LLM)_")

    return "\n".join(lines)


def build_llm_prompt(obs):
    """Build a prompt for the LLM summarizer from observations."""
    tool_lines = []
    for o in obs[-40:]:  # last 40 observations to stay within token budget
        t = o.get("tool", "?")
        s = o.get("summary", "")[:120]
        ts = o.get("time", "")
        tool_lines.append(f"[{ts}] {t}: {s}")

    obs_text = "\n".join(tool_lines)
    return (
        "You are summarizing a Claude Code session for the next session's context.\n"
        "Based on the tool usage log below, write a concise session summary (8-15 lines):\n"
        "- What was the main goal/task?\n"
        "- What was accomplished?\n"
        "- Key files created or modified\n"
        "- Any decisions made or problems solved\n"
        "- What should the next session pick up from?\n"
        "Tag with 1-3 hashtags (e.g. #feature, #bugfix, #research)\n\n"
        f"Tool log:\n{obs_text}\n\n"
        "Write the summary now:"
    )


def try_gemini(prompt):
    """Attempt to generate summary via Gemini CLI."""
    try:
        result = subprocess.run(
            ["gemini", "-p", prompt],
            capture_output=True, text=True, timeout=25
        )
        if result.returncode == 0 and result.stdout.strip():
            return result.stdout.strip()
    except (FileNotFoundError, subprocess.TimeoutExpired):
        pass
    return None


def try_ollama(prompt):
    """Attempt to generate summary via Ollama (llama3)."""
    payload = json.dumps({"model": "llama3", "prompt": prompt, "stream": False})
    try:
        result = subprocess.run(
            ["ollama", "run", "llama3", prompt],
            capture_output=True, text=True, timeout=45
        )
        if result.returncode == 0 and result.stdout.strip():
            return result.stdout.strip()
    except (FileNotFoundError, subprocess.TimeoutExpired):
        pass
    return None


def archive_summary(content):
    """Save the summary to the permanent archive."""
    ARCHIVE_DIR.mkdir(parents=True, exist_ok=True)
    archive_path = ARCHIVE_DIR / f"{TODAY}-{NOW}-session.md"
    with open(archive_path, "w") as f:
        f.write(content)
    return archive_path


def save_buffer(content):
    """Save summary to session-buffer.md for SessionStart injection."""
    with open(BUFFER_FILE, "w") as f:
        f.write(content)


def main():
    obs = load_observations()

    if not obs:
        print('{"continue": true}', file=sys.stdout)
        print("No observations to summarize.", file=sys.stderr)
        return

    print(f"Summarizing {len(obs)} observations...", file=sys.stderr)

    prompt = build_llm_prompt(obs)
    summary = None

    # Tier 1: Gemini CLI
    summary = try_gemini(prompt)
    if summary:
        print("Summary generated via Gemini CLI.", file=sys.stderr)

    # Tier 2: Ollama
    if not summary:
        summary = try_ollama(prompt)
        if summary:
            print("Summary generated via Ollama.", file=sys.stderr)

    # Tier 3: Structured fallback
    if not summary:
        summary = build_structured_summary(obs)
        print("Summary generated via structured fallback.", file=sys.stderr)

    if not summary:
        print('{"continue": true}', file=sys.stdout)
        return

    # Prepend metadata header
    header = (
        f"# Session Summary\n"
        f"**Date:** {TODAY}  **Time:** {NOW.replace('-', ':')}  "
        f"**Observations:** {len(obs)}\n\n"
    )
    full_summary = header + summary

    archive_path = archive_summary(full_summary)
    save_buffer(full_summary)

    print(f"Session archived to: {archive_path}", file=sys.stderr)
    print('{"continue": true}', file=sys.stdout)


if __name__ == "__main__":
    main()
